Feature/haxagono module
gabriellmb05/tech-challenge pull request #3
Opened 2024-12-26 06:28 UTC by tgobmdev

2024-12-27 00:13 UTC, gabriellmb05 commented
@tgobmdev , eu coloquei alguns comentários no que consegui revisar. Um ponto é que não consegui subir o postgres e nem executar a aplicação via intellij. Você está conseguindo?
De qualquer forma a nova estrutura ficou muito boa, mandou benzão.

2024-12-27 00:14 UTC, gabriellmb05 requested changes

2024-12-27 00:16 UTC, tgobmdev commented
Consegui sim, depois alinhamos e ajudo a rodar e bem tranquilo

2024-12-28 15:06 UTC, samuelrosacv reviewed
Não consegui subir a aplicação.

2024-12-28 21:01 UTC, gabriellmb05 approved these changes

2025-01-03 01:19 UTC, merged